# Generated by Django 3.0.5 on 2021-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
