# Generated by Django 3.0.5 on 2021-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingprofile_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
