# Generated by Django 3.0.5 on 2020-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
