# Generated by Django 3.0.5 on 2020-09-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_contentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='requried',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
