# Generated by Django 3.0.5 on 2020-09-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200905_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='ContentCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ContentCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='requried',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
