# Generated by Django 3.0.5 on 2020-09-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200908_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='requried',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
