# Generated by Django 3.0.5 on 2020-09-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200908_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
