# Generated by Django 3.0.5 on 2020-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Aisle_number',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Shelf_number',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Shelf_side',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
