# Generated by Django 3.0.5 on 2020-09-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200911_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='additional_content_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
