# Generated by Django 3.0.5 on 2020-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_contentcategory_additional_content_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='additional_content_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
