# Generated by Django 3.0.5 on 2020-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200914_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcategory',
            old_name='additional_content_price',
            new_name='required_content_price',
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='additional_content_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
