# Generated by Django 3.0.5 on 2020-09-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_producttax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcategory',
            name='required_content_price',
        ),
    ]
