# Generated by Django 3.0.5 on 2020-09-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_contentcategory_required_content_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttax',
            name='Tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
