# Generated by Django 3.0.5 on 2020-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_auto_20200703_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='delivery_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
