# Generated by Django 3.0.5 on 2020-10-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0011_shopprofile_delivery_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ShopCategories/')),
            ],
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopkeeper.ShopCategories'),
        ),
    ]
