# Generated by Django 3.0.5 on 2020-10-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0013_shopprofile_personal_pickup_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='personal_pickup_limit',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
