# Generated by Django 3.0.5 on 2020-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewallet',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
