# Generated by Django 3.0.5 on 2020-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_auto_20201023_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewallet',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
