# Generated by Django 3.0.5 on 2020-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='id_number',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
