# Generated by Django 3.0.5 on 2020-08-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_content'),
        ('cart', '0006_auto_20200731_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='content',
            field=models.ManyToManyField(to='product.Content'),
        ),
    ]
