# Generated by Django 3.0.5 on 2020-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200907_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
