# Generated by Django 2.1.5 on 2020-07-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_auto_20200703_1736'),
        ('orders', '0007_auto_20200709_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.ShopProfile'),
            preserve_default=False,
        ),
    ]
