# Generated by Django 2.1.5 on 2020-07-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200709_0829'),
        ('orders', '0014_auto_20200716_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerProfile'),
            preserve_default=False,
        ),
    ]
