# Generated by Django 2.1.5 on 2020-07-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
