# Generated by Django 2.1.5 on 2020-07-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
