# Generated by Django 2.1.5 on 2020-07-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('ONLINE', 'online'), ('PICK FROM SHOP', 'pick from shop')], default='online', max_length=120),
        ),
    ]
