# Generated by Django 2.1.5 on 2020-07-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CREATED', 'created'), ('ORDER READY', 'order ready'), ('ACCEPTED BY SHOP', 'acceped by shop'), ('OUT FOR DELIVERY', 'out for delivery'), ('SHIPPED', 'shipped'), ('REFUNDED', 'refunded'), ('CANCELLED', 'cancelled')], default='created', max_length=120),
        ),
    ]
