# Generated by Django 2.1.5 on 2020-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200725_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ready',
            field=models.BooleanField(default=False),
        ),
    ]
