# Generated by Django 2.1.5 on 2020-07-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_acceped_by_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='acceped_by_shop',
            new_name='accepted_by_shop',
        ),
    ]
