# Generated by Django 2.1.5 on 2020-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200725_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('DOORSTEP DELIVERY', 'doorstep delivery'), ('PICK FROM SHOP', 'pick from shop')], default='doorstep delivery', max_length=120),
        ),
    ]
