# Generated by Django 3.0.5 on 2020-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200727_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_schedule',
            field=models.CharField(blank=True, default='no schedule', max_length=120, null=True),
        ),
    ]
