# Generated by Django 3.0.5 on 2020-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_delivery_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_preparation_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
