# Generated by Django 3.0.5 on 2020-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200825_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('HOME DELIVERY', 'home delivery'), ('PERSONAL PICKUP', 'personal pickup')], default='home delivery', max_length=120),
        ),
    ]
