# Generated by Django 3.0.5 on 2020-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20200825_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
