# Generated by Django 3.0.5 on 2020-09-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
        ('orders', '0029_order_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appoint_collector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.CollectorProfile'),
        ),
    ]
