# Generated by Django 3.0.5 on 2020-09-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200924_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
